import type { PaperClawPluginManifestV1 } from "@kesarcloud/plugin-sdk";
import {
  DEFAULT_CONFIG,
  DEFAULT_SCOPES,
  EXPORT_NAMES,
  PAGE_ROUTE,
  PLUGIN_ID,
  PLUGIN_VERSION,
  SLOT_IDS,
  TOOL_NAMES,
} from "./constants.js";

const stringParam = { type: "string" } as const;
const objectParam = { type: "object" } as const;

const manifest: PaperClawPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: PLUGIN_VERSION,
  displayName: "Canva",
  description: "Connects PaperClaw agents to Canva Connect APIs for designs, assets, brand templates, exports, folders, comments, imports, and resizes.",
  author: "PaperClaw",
  categories: ["connector", "automation", "workspace", "ui"],
  capabilities: [
    "http.outbound",
    "secrets.read-ref",
    "secrets.write-ref",
    "agent.tools.register",
    "plugin.state.read",
    "plugin.state.write",
    "activity.log.write",
    "instance.settings.register",
    "ui.page.register",
    "ui.dashboardWidget.register",
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  instanceConfigSchema: {
    type: "object",
    properties: {
      clientId: {
        type: "string",
        title: "Canva Client ID",
        default: DEFAULT_CONFIG.clientId,
        description: "Client ID from your Canva developer integration.",
      },
      clientSecretRef: {
        type: "string",
        format: "secret-ref",
        title: "Canva Client Secret Reference",
        default: DEFAULT_CONFIG.clientSecretRef,
        description: "PaperClaw secret reference containing the Canva client secret.",
      },
      refreshTokenSecretRef: {
        type: "string",
        format: "secret-ref",
        title: "Canva Refresh Token Secret Reference",
        default: DEFAULT_CONFIG.refreshTokenSecretRef,
        description: "PaperClaw secret reference created by the Canva OAuth setup flow.",
      },
      connectedCompanyId: {
        type: "string",
        title: "Connected Company ID",
        default: DEFAULT_CONFIG.connectedCompanyId,
        description: "Company that owns the Canva OAuth connection.",
      },
      connectedAt: {
        type: "string",
        title: "Connected At",
        default: DEFAULT_CONFIG.connectedAt,
      },
      connectedUserId: {
        type: "string",
        title: "Connected Canva User ID",
        default: DEFAULT_CONFIG.connectedUserId,
      },
      connectedDisplayName: {
        type: "string",
        title: "Connected Canva User",
        default: DEFAULT_CONFIG.connectedDisplayName,
      },
      redirectUri: {
        type: "string",
        title: "Redirect URI",
        default: DEFAULT_CONFIG.redirectUri,
        description: "Canva OAuth redirect URI. Add this exact URL in the Canva developer portal.",
      },
      enabledScopes: {
        type: "array",
        title: "Enabled OAuth Scopes",
        default: DEFAULT_CONFIG.enabledScopes,
        items: { type: "string", enum: [...DEFAULT_SCOPES] },
      },
      dryRun: {
        type: "boolean",
        title: "Dry Run",
        default: DEFAULT_CONFIG.dryRun,
        description: "When enabled, mutating Canva tools return the planned request without changing Canva.",
      },
      maxPollAttempts: {
        type: "number",
        title: "Max Poll Attempts",
        default: DEFAULT_CONFIG.maxPollAttempts,
        minimum: 1,
        maximum: 30,
      },
      requestTimeoutMs: {
        type: "number",
        title: "Request Timeout Milliseconds",
        default: DEFAULT_CONFIG.requestTimeoutMs,
        minimum: 5000,
        maximum: 120000,
      },
    },
  },
  tools: [
    { name: TOOL_NAMES.getCurrentUser, displayName: "Canva Current User", description: "Return the current Canva user identity.", parametersSchema: { type: "object", properties: {} } },
    { name: TOOL_NAMES.getUserProfile, displayName: "Canva User Profile", description: "Return the current Canva user's profile.", parametersSchema: { type: "object", properties: {} } },
    { name: TOOL_NAMES.getUserCapabilities, displayName: "Canva User Capabilities", description: "Return API capabilities for the current Canva user.", parametersSchema: { type: "object", properties: {} } },
    { name: TOOL_NAMES.listDesigns, displayName: "List Canva Designs", description: "List Canva designs visible to the connected user.", parametersSchema: { type: "object", properties: { query: stringParam, continuation: stringParam, ownership: stringParam, sortBy: stringParam } } },
    { name: TOOL_NAMES.getDesign, displayName: "Get Canva Design", description: "Get Canva design metadata by design ID.", parametersSchema: { type: "object", properties: { designId: stringParam }, required: ["designId"] } },
    { name: TOOL_NAMES.createDesign, displayName: "Create Canva Design", description: "Create a new Canva design.", parametersSchema: { type: "object", properties: { designType: objectParam, title: stringParam, assetId: stringParam }, required: ["designType"] } },
    { name: TOOL_NAMES.getDesignPages, displayName: "Get Canva Design Pages", description: "List pages in a Canva design.", parametersSchema: { type: "object", properties: { designId: stringParam }, required: ["designId"] } },
    { name: TOOL_NAMES.getDesignExportFormats, displayName: "Get Canva Export Formats", description: "List supported export formats for a Canva design.", parametersSchema: { type: "object", properties: { designId: stringParam }, required: ["designId"] } },
    { name: TOOL_NAMES.createExportJob, displayName: "Create Canva Export Job", description: "Start an async Canva design export job.", parametersSchema: { type: "object", properties: { designId: stringParam, format: objectParam, pages: { type: "array" }, poll: { type: "boolean" } }, required: ["designId", "format"] } },
    { name: TOOL_NAMES.getExportJob, displayName: "Get Canva Export Job", description: "Get a Canva export job by ID.", parametersSchema: { type: "object", properties: { exportId: stringParam }, required: ["exportId"] } },
    { name: TOOL_NAMES.getAsset, displayName: "Get Canva Asset", description: "Get Canva asset metadata by asset ID.", parametersSchema: { type: "object", properties: { assetId: stringParam }, required: ["assetId"] } },
    { name: TOOL_NAMES.uploadAssetFromUrl, displayName: "Upload Canva Asset From URL", description: "Start a Canva URL asset upload job.", parametersSchema: { type: "object", properties: { url: stringParam, name: stringParam, tags: { type: "array" }, poll: { type: "boolean" } }, required: ["url", "name"] } },
    { name: TOOL_NAMES.uploadAssetBytes, displayName: "Upload Canva Asset Bytes", description: "Upload base64 asset bytes to Canva.", parametersSchema: { type: "object", properties: { base64Content: stringParam, name: stringParam, mimeType: stringParam, tags: { type: "array" }, poll: { type: "boolean" } }, required: ["base64Content", "name", "mimeType"] } },
    { name: TOOL_NAMES.updateAsset, displayName: "Update Canva Asset", description: "Update a Canva asset name or tags.", parametersSchema: { type: "object", properties: { assetId: stringParam, name: stringParam, tags: { type: "array" } }, required: ["assetId"] } },
    { name: TOOL_NAMES.deleteAsset, displayName: "Delete Canva Asset", description: "Move a Canva asset to trash.", parametersSchema: { type: "object", properties: { assetId: stringParam }, required: ["assetId"] } },
    { name: TOOL_NAMES.listBrandTemplates, displayName: "List Canva Brand Templates", description: "List Canva brand templates.", parametersSchema: { type: "object", properties: { continuation: stringParam, query: stringParam, brandTemplateIds: { type: "array" } } } },
    { name: TOOL_NAMES.getBrandTemplate, displayName: "Get Canva Brand Template", description: "Get Canva brand template metadata.", parametersSchema: { type: "object", properties: { brandTemplateId: stringParam }, required: ["brandTemplateId"] } },
    { name: TOOL_NAMES.getBrandTemplateDataset, displayName: "Get Canva Brand Template Dataset", description: "Get autofill dataset schema for a brand template.", parametersSchema: { type: "object", properties: { brandTemplateId: stringParam }, required: ["brandTemplateId"] } },
    { name: TOOL_NAMES.createAutofillJob, displayName: "Create Canva Autofill Job", description: "Start a Canva design autofill job.", parametersSchema: { type: "object", properties: { brandTemplateId: stringParam, title: stringParam, data: objectParam, poll: { type: "boolean" } }, required: ["brandTemplateId", "data"] } },
    { name: TOOL_NAMES.getAutofillJob, displayName: "Get Canva Autofill Job", description: "Get a Canva autofill job.", parametersSchema: { type: "object", properties: { jobId: stringParam }, required: ["jobId"] } },
    { name: TOOL_NAMES.createDesignImportJob, displayName: "Create Canva Import Job", description: "Start a design import job.", parametersSchema: { type: "object", properties: { importMetadata: objectParam, base64Content: stringParam, mimeType: stringParam, poll: { type: "boolean" } }, required: ["importMetadata", "base64Content", "mimeType"] } },
    { name: TOOL_NAMES.getDesignImportJob, displayName: "Get Canva Import Job", description: "Get a design import job.", parametersSchema: { type: "object", properties: { jobId: stringParam }, required: ["jobId"] } },
    { name: TOOL_NAMES.createUrlImportJob, displayName: "Create Canva URL Import Job", description: "Start a URL design import job.", parametersSchema: { type: "object", properties: { url: stringParam, title: stringParam, poll: { type: "boolean" } }, required: ["url"] } },
    { name: TOOL_NAMES.getUrlImportJob, displayName: "Get Canva URL Import Job", description: "Get a URL import job.", parametersSchema: { type: "object", properties: { jobId: stringParam }, required: ["jobId"] } },
    { name: TOOL_NAMES.createResizeJob, displayName: "Create Canva Resize Job", description: "Start a Canva design resize job.", parametersSchema: { type: "object", properties: { designId: stringParam, targetDimensions: objectParam, title: stringParam, poll: { type: "boolean" } }, required: ["designId", "targetDimensions"] } },
    { name: TOOL_NAMES.getResizeJob, displayName: "Get Canva Resize Job", description: "Get a Canva resize job.", parametersSchema: { type: "object", properties: { jobId: stringParam }, required: ["jobId"] } },
    { name: TOOL_NAMES.createFolder, displayName: "Create Canva Folder", description: "Create a Canva folder.", parametersSchema: { type: "object", properties: { name: stringParam, parentFolderId: stringParam }, required: ["name"] } },
    { name: TOOL_NAMES.getFolder, displayName: "Get Canva Folder", description: "Get Canva folder metadata.", parametersSchema: { type: "object", properties: { folderId: stringParam }, required: ["folderId"] } },
    { name: TOOL_NAMES.updateFolder, displayName: "Update Canva Folder", description: "Update a Canva folder.", parametersSchema: { type: "object", properties: { folderId: stringParam, name: stringParam }, required: ["folderId", "name"] } },
    { name: TOOL_NAMES.deleteFolder, displayName: "Delete Canva Folder", description: "Delete a Canva folder.", parametersSchema: { type: "object", properties: { folderId: stringParam }, required: ["folderId"] } },
    { name: TOOL_NAMES.listFolderItems, displayName: "List Canva Folder Items", description: "List items in a Canva folder.", parametersSchema: { type: "object", properties: { folderId: stringParam, continuation: stringParam }, required: ["folderId"] } },
    { name: TOOL_NAMES.moveFolderItem, displayName: "Move Canva Folder Item", description: "Move a Canva design, asset, or folder.", parametersSchema: { type: "object", properties: { toFolderId: stringParam, itemId: stringParam, itemType: stringParam }, required: ["toFolderId", "itemId", "itemType"] } },
    { name: TOOL_NAMES.createCommentThread, displayName: "Create Canva Comment Thread", description: "Create a comment thread on a Canva design.", parametersSchema: { type: "object", properties: { designId: stringParam, message: stringParam, assigneeId: stringParam }, required: ["designId", "message"] } },
    { name: TOOL_NAMES.listCommentReplies, displayName: "List Canva Comment Replies", description: "List replies in a Canva comment thread.", parametersSchema: { type: "object", properties: { designId: stringParam, threadId: stringParam, continuation: stringParam }, required: ["designId", "threadId"] } },
    { name: TOOL_NAMES.createCommentReply, displayName: "Create Canva Comment Reply", description: "Reply to a Canva comment thread.", parametersSchema: { type: "object", properties: { designId: stringParam, threadId: stringParam, message: stringParam }, required: ["designId", "threadId", "message"] } },
  ],
  ui: {
    slots: [
      {
        type: "page",
        id: SLOT_IDS.page,
        displayName: "Canva",
        exportName: EXPORT_NAMES.page,
        routePath: PAGE_ROUTE,
      },
      {
        type: "settingsPage",
        id: SLOT_IDS.settingsPage,
        displayName: "Canva",
        exportName: EXPORT_NAMES.settingsPage,
      },
      {
        type: "dashboardWidget",
        id: SLOT_IDS.dashboardWidget,
        displayName: "Canva",
        exportName: EXPORT_NAMES.dashboardWidget,
      },
    ],
    launchers: [
      {
        id: "canva-page",
        displayName: "Canva",
        placementZone: "sidebar",
        action: {
          type: "navigate",
          target: PAGE_ROUTE,
        },
      },
    ],
  },
};

export default manifest;
