import type { Db } from "@kesarcloud/db";
import type {
  AgentToolsMdSyncResult,
  ToolPermissionPolicy,
} from "@kesarcloud/shared";
import { HttpError } from "../errors.js";
import { agentInstructionsService } from "./agent-instructions.js";
import {
  loadDefaultAgentInstructionsBundle,
  resolveDefaultAgentInstructionsBundleRole,
} from "./default-agent-instructions.js";
import { agentService } from "./agents.js";
import { toolPermissionService } from "./tool-permissions.js";

export const AGENT_TOOLS_MD_PATH = "TOOLS.md";
export const AGENT_TOOLS_MD_GENERATED_MARKER = "<!-- paperclaw:generated-tools-md v1 -->";

type ActorInfo = {
  actorType: "agent" | "user" | "system" | "plugin";
  actorId: string;
  agentId?: string | null;
  runId?: string | null;
};

type AgentLike = {
  id: string;
  companyId: string;
  name: string;
  role: string;
  title: string | null;
  status: string;
  adapterConfig: Record<string, unknown>;
};

function effectLabel(effect: ToolPermissionPolicy["effect"]) {
  switch (effect) {
    case "allow":
      return "allowed";
    case "approval_required":
      return "approval required";
    case "budget_limited":
      return "budget limited";
    case "deny":
      return "denied";
    case "inherit":
      return "inherit";
    default:
      return effect;
  }
}

function formatScope(policy: ToolPermissionPolicy) {
  if (policy.pluginKey && policy.toolName) return `${policy.pluginKey}:${policy.toolName}`;
  if (policy.pluginKey) return `${policy.pluginKey}:*`;
  return "all plugin tools";
}

function formatBudget(policy: ToolPermissionPolicy) {
  if (policy.effect !== "budget_limited" || !policy.budgetLimit) return "";
  return ` (${policy.budgetLimit.amount} ${policy.budgetLimit.metric.replaceAll("_", " ")} / calendar month UTC)`;
}

function bullet(policy: ToolPermissionPolicy) {
  const disabled = policy.enabled ? "" : " disabled";
  return `- \`${formatScope(policy)}\` -- ${effectLabel(policy.effect)}${formatBudget(policy)}${disabled}`;
}

function sortedPolicies(policies: ToolPermissionPolicy[]) {
  return [...policies].sort((left, right) => {
    const leftKey = `${left.subjectType}:${left.subjectId ?? ""}:${left.pluginKey ?? ""}:${left.toolName ?? ""}`;
    const rightKey = `${right.subjectType}:${right.subjectId ?? ""}:${right.pluginKey ?? ""}:${right.toolName ?? ""}`;
    return leftKey.localeCompare(rightKey);
  });
}

export function renderAgentToolsMarkdown(input: {
  agent: Pick<AgentLike, "id" | "name" | "role" | "title">;
  policies: ToolPermissionPolicy[];
  generatedAt?: Date;
}) {
  const generatedAt = input.generatedAt ?? new Date();
  const agentPolicies = sortedPolicies(input.policies.filter(
    (policy) => policy.subjectType === "agent" && policy.subjectId === input.agent.id,
  ));
  const companyPolicies = sortedPolicies(input.policies.filter(
    (policy) => policy.subjectType === "company" && policy.subjectId === null,
  ));

  const agentTitle = input.agent.title ? `${input.agent.name} (${input.agent.title})` : input.agent.name;
  const lines = [
    AGENT_TOOLS_MD_GENERATED_MARKER,
    "",
    "# Tools",
    "",
    "Generated by PaperClaw from backend tool permission policies.",
    "",
    `Agent: ${agentTitle}`,
    `Role: ${input.agent.role}`,
    `Updated: ${generatedAt.toISOString()}`,
    "",
    "## Rules",
    "",
    "- Backend tool permissions are the source of truth; this file is a context summary.",
    "- Use allowed tools directly.",
    "- For approval-required tools, request or wait for approval before retrying the tool call.",
    "- For budget-limited tools, respect the listed execution window.",
    "- Denied or unlisted plugin tools are not available unless a manager or the Board changes policy.",
    "",
    "## Agent Assignments",
    "",
    agentPolicies.length > 0
      ? agentPolicies.map(bullet).join("\n")
      : "No explicit agent tool assignments.",
    "",
    "## Company Policies",
    "",
    companyPolicies.length > 0
      ? companyPolicies.map(bullet).join("\n")
      : "No explicit company-level tool policies. Runtime default is approval required.",
    "",
    "If a task needs a missing tool, ask your manager or the Board to assign it.",
    "",
  ];

  return lines.join("\n");
}

function isWritableGeneratedToolsFile(content: string) {
  return (
    content.includes(AGENT_TOOLS_MD_GENERATED_MARKER)
    || content.includes("(Your tools will go here")
    || content.trim() === "# Tools"
  );
}

async function ensureDefaultInstructionsBundleIfMissing(
  db: Db,
  agent: AgentLike,
): Promise<AgentLike> {
  const instructions = agentInstructionsService();
  const bundle = await instructions.getBundle(agent);
  if (bundle.rootPath || bundle.files.length > 0) return agent;

  const files = await loadDefaultAgentInstructionsBundle(resolveDefaultAgentInstructionsBundleRole(agent.role));
  const materialized = await instructions.materializeManagedBundle(agent, files, {
    entryFile: "AGENTS.md",
    replaceExisting: false,
  });
  const updated = await agentService(db).update(agent.id, {
    adapterConfig: materialized.adapterConfig,
  });
  return updated ?? { ...agent, adapterConfig: materialized.adapterConfig };
}

export function agentToolsMdService(db: Db) {
  const agents = agentService(db);
  const toolPermissions = toolPermissionService(db);
  const instructions = agentInstructionsService();

  async function syncAgent(agent: AgentLike, actor?: ActorInfo | null): Promise<AgentToolsMdSyncResult> {
    const target = await ensureDefaultInstructionsBundleIfMissing(db, agent);
    try {
      const existing = await instructions.readFile(target, AGENT_TOOLS_MD_PATH).catch((err) => {
        if (err instanceof HttpError && err.status === 404) return null;
        throw err;
      });
      if (existing && !isWritableGeneratedToolsFile(existing.content)) {
        return {
          agentId: target.id,
          status: "skipped_custom",
          path: AGENT_TOOLS_MD_PATH,
          reason: "TOOLS.md contains custom content without the PaperClaw generated marker.",
          updatedAt: null,
        };
      }

      const policies = await toolPermissions.listPolicies(target.companyId);
      const content = renderAgentToolsMarkdown({ agent: target, policies });
      const result = await instructions.writeFile(target, AGENT_TOOLS_MD_PATH, content);
      await agents.update(
        target.id,
        { adapterConfig: result.adapterConfig },
        {
          recordRevision: {
            createdByAgentId: actor?.agentId ?? null,
            createdByUserId: actor?.actorType === "user" ? actor.actorId : null,
            source: "agent_tools_md_sync",
          },
        },
      );
      return {
        agentId: target.id,
        status: "synced",
        path: AGENT_TOOLS_MD_PATH,
        updatedAt: new Date(),
      };
    } catch (err) {
      return {
        agentId: target.id,
        status: "skipped_unavailable",
        path: AGENT_TOOLS_MD_PATH,
        reason: err instanceof Error ? err.message : String(err),
        updatedAt: null,
      };
    }
  }

  async function syncCompany(companyId: string, actor?: ActorInfo | null): Promise<AgentToolsMdSyncResult[]> {
    const list = await agents.list(companyId);
    const activeAgents = list.filter((agent) => agent.status !== "terminated");
    const results: AgentToolsMdSyncResult[] = [];
    for (const agent of activeAgents) {
      results.push(await syncAgent(agent, actor));
    }
    return results;
  }

  return {
    syncAgent,
    syncCompany,
  };
}
